- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,suresh,raheem,joseph"
  tasks:
  - name: check undefined vars
    ansible.builtin.debug:
      msg: "Hello ,{{ person | default('Ramesh') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello ,{{ persons }}"
