- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,suresh,raheem,joseph"
  tasks:
  - name: check undefined vars
    ansible.builtin.debug:
      msg: "Hello ,{{ person | default('Ramesh') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello ,{{ persons | split(',') }}"

  - name: convert map to list
    vars:
      course:
        name: ansible
        duration: 10HR
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "course info: {{ course | dict2items }}"

  - name: convert list to map
    vars:
      course:
        - ansible
        - 10HR
        - sivakumar
    ansible.builtin.debug:
      msg: "course info: {{ course | items2dict }}"
