- name: variables
  hosts: local
  connection: local
  vars: 
    Course: Ansible
    Duration: 120H
    Trainer: sivakumar
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Hello Course: {{Course}} Duration: {{Duration}} Trainer: {{Trainer}}"


  - name: print course info again
    ansible.builtin.debug:
      msg: "Hello Course: {{Course}} Duration: {{Duration}} Trainer: {{Trainer}}"